### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by MK5555** [ch3ck/ydl#29]
I try git clone and make. But an error has occurred. How to fix it?
+ clean
+ fmt
+ vet
+ build
CGO_ENABLED=1 go build -tags " cgo" .
+ test
=== RUN   TestApi
time="2020-04-12T20:48:22+03:00" level=error msg="Unable to create goutube object https://www.youtube.com/watch?v=lWEbEtr_Vng: fork/exec youtube-dl: no such file or directory"
    TestApi: download_test.go:27: videoId(0): expected "lWEbEtr_Vng", actual "fork/exec youtube-dl: no such file or directory"
time="2020-04-12T20:48:22+03:00" level=error msg="Unable to create goutube object https://www.youtube.com/watch?v=ALWmcO8S-dc: fork/exec youtube-dl: no such file or directory"
    TestApi: download_test.go:27: videoId(1): expected "ALWmcO8S-dc", actual "fork/exec youtube-dl: no such file or directory"
time="2020-04-12T20:48:22+03:00" level=error msg="Unable to create goutube object : fork/exec youtube-dl: no such file or directory"
    TestApi: download_test.go:27: videoId(2): expected "", actual "fork/exec youtube-dl: no such file or directory"
time="2020-04-12T20:48:22+03:00" level=error msg="Unable to create goutube object https://www.facebook.com/mark/videos?v=RDHpNluHOAJFA: fork/exec youtube-dl: no such file or directory"
    TestApi: download_test.go:27: videoId(3): expected "", actual "fork/exec youtube-dl: no such file or directory"
time="2020-04-12T20:48:22+03:00" level=error msg="Unable to create goutube object https://www.youtube.com/watch?v=ALWmcO8S-dc: fork/exec youtube-dl: no such file or directory"
    TestApi: download_test.go:27: videoId(4): expected "ALWmcO8S-dc", actual "fork/exec youtube-dl: no such file or directory"
time="2020-04-12T20:48:22+03:00" level=error msg="Unable to create goutube object https://www.wsj.com/articles/trump-administration-wont-withdraw-from-paris-climate-deal-1505593922: fork/exec youtube-dl: no such file or directory"
    TestApi: download_test.go:27: videoId(5): expected "", actual "fork/exec youtube-dl: no such file or directory"
time="2020-04-12T20:48:22+03:00" level=error msg="Unable to create goutube object https://vimeo.com/101522071: fork/exec youtube-dl: no such file or directory"
    TestApi: download_test.go:27: videoId(6): expected "", actual "fork/exec youtube-dl: no such file or directory"
--- FAIL: TestApi (0.00s)
FAIL
FAIL	github.com/ch3ck/youtube-dl	0.007s
FAIL
Makefile:26: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by netrebel** [comment]
I also got an error on `make`:

```
make
+ clean
+ fmt
download.go
download.go
+ vet
+ build
CGO_ENABLED=1 go build -tags " cgo" .
+ test
=== RUN   TestApi
time="2020-04-27T16:10:23-07:00" level=error msg="Unable to create goutube object https://www.youtube.com/watch?v=lWEbEtr_Vng: exit status 2"
    TestApi: download_test.go:27: videoId(0): expected "lWEbEtr_Vng", actual "exit status 2"
time="2020-04-27T16:10:23-07:00" level=error msg="Unable to create goutube object https://www.youtube.com/watch?v=ALWmcO8S-dc: exit status 2"
    TestApi: download_test.go:27: videoId(1): expected "ALWmcO8S-dc", actual "exit status 2"
time="2020-04-27T16:10:23-07:00" level=error msg="Unable to create goutube object : exit status 2"
    TestApi: download_test.go:27: videoId(2): expected "", actual "exit status 2"
time="2020-04-27T16:10:23-07:00" level=error msg="Unable to create goutube object https://www.facebook.com/mark/videos?v=RDHpNluHOAJFA: exit status 2"
    TestApi: download_test.go:27: videoId(3): expected "", actual "exit status 2"
time="2020-04-27T16:10:23-07:00" level=error msg="Unable to create goutube object https://www.youtube.com/watch?v=ALWmcO8S-dc: exit status 2"
    TestApi: download_test.go:27: videoId(4): expected "ALWmcO8S-dc", actual "exit status 2"
time="2020-04-27T16:10:23-07:00" level=error msg="Unable to create goutube object https://www.wsj.com/articles/trump-administration-wont-withdraw-from-paris-climate-deal-1505593922: exit status 2"
    TestApi: download_test.go:27: videoId(5): expected "", actual "exit status 2"
time="2020-04-27T16:10:23-07:00" level=error msg="Unable to create goutube object https://vimeo.com/101522071: exit status 2"
    TestApi: download_test.go:27: videoId(6): expected "", actual "exit status 2"
--- FAIL: TestApi (0.10s)
FAIL
FAIL    github.com/ch3ck/youtube-dl     0.109s
FAIL
make: *** [test] Error 1
```

Same if I just try to run the binary:
```
youtube-dl -id xfLVxx_lBLU
ERRO[0000] Unable to create goutube object xfLVxx_lBLU: exit status 2
ERRO[0000] Unable to beginDownload: exit status 2
```

**Comment by ch3ck** [comment]
@netrebel @MK5555 you need to install the youtube-dl package as a dependency before running this.

**Comment by ch3ck** [comment]
@MK5555 fixed!
